### ISSUE TITLE
LIE Report Attributes Changes

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#33]
There is a requirement change in LIE Report .
Please see the excel sheet for the revised set of attributes.
[Enquiry Portal Attributes v 0.5.xlsx](https://github.com/LeanThoughts/lms-enquiry/files/5936390/Enquiry.Portal.Attributes.v.0.5.xlsx)

These are the new attributes. Of these, 4 fields (in bold) are display only. 
ReportType | Dropdown
DateofReceipt | Date
InvoiceDate | Date
InvoiceNo | String(20)
FeeAmount | Amount (Formatted)
StatusofFeePaid | Dropdown
**SAP FI   Invoice Date | Date
SAP FI   Invoice Number | String(20)
Fee   Amount Raised on Customer | Amount (Formatted)
StatusofFeeReceipt | Dropdown**
DocumentTitle | String(20)
DocumentContent | Blob
NextReportDate | Date

**Comment by gguptha** [comment]
Fixed.
