### ISSUE TITLE
Add LIE : Business Partner

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#36]
Business Partner Should be a drop down.  Dropdown values are loaded from the Partner Table using the Bus. Partner Role.
Bus. Partner Name is a display only field and it is populated based on the drop down selection
See attached excel sheet for details. 

![image](https://user-images.githubusercontent.com/22815486/107111549-f7ef0b00-6876-11eb-9310-34c523c1785e.png)
[BupaRoles.xlsx](https://github.com/LeanThoughts/lms-enquiry/files/5936429/BupaRoles.xlsx)

**Comment by gguptha** [comment]
Fixed.
