### ISSUE TITLE
LFA Dialog Screen : Bus. Partner Drop Down and Field Validation

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#41]
1. Business Partner should be a drop down just like LIE 
2. Date Field Validation 
3. Email Validation
![image](https://user-images.githubusercontent.com/22815486/107112294-8d40ce00-687c-11eb-972a-7ae942ef0fa9.png)

**Comment by gguptha** [comment]
Fixed.
