### ISSUE TITLE
LFA Report : Attribute Changes

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#43]
Just like LIE, the LFA Report Dialog window should be as follow:

![image](https://user-images.githubusercontent.com/22815486/107112388-47d0d080-687d-11eb-95b4-2172f9432723.png)

Following fields shall be display only:

1. SAP FI   Invoice Date
2. SAP FI   Invoice Number
3. Fee   Amount Raised on Customer
4. StatusofFeeReceipt

**Comment by gguptha** [comment]
Fixed.
