### ISSUE TITLE
LIE, LFA, TRA Dialog Screens : Field Length

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#48]
Limit the length of the fields as per the specification in the attached excel.
[Enquiry Portal Attributes v 0.5.xlsx](https://github.com/LeanThoughts/lms-enquiry/files/5936475/Enquiry.Portal.Attributes.v.0.5.xlsx)

![image](https://user-images.githubusercontent.com/22815486/107113004-b9ab1900-6881-11eb-9909-08df35bf28e4.png)

**Comment by gguptha** [comment]
Fixed.
