### ISSUE TITLE
Security Compliance Dialog Window

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#53]
1. Limit field length as per the DDIC excel 
2. Validate field as per the the DDIC excel 
3. Holding Percentage Field Label is not correct 
4. Amount Field Validation 
5. Numeric Field Validation 

![image](https://user-images.githubusercontent.com/22815486/107113740-d85fde80-6886-11eb-88ee-3896f6ec47fd.png)

**Comment by gguptha** [comment]
Fixed.
