### ISSUE TITLE
Financial Covenants : Column Values and Field Foramt

### ISSUE THREAD

**Issue by LeanThoughts** [LeanThoughts/lms-enquiry#71]
1. "Type" Column should display the text of the drop down value 
2. "Debt Equity Ratio"< "DSCR", "TOL/TNW" should be number formatted with % Symbol 
![image](https://user-images.githubusercontent.com/22815486/109772125-a5113500-7c23-11eb-9840-dd5fe06b3e12.png)

**Comment by gguptha** [comment]
Fixed.
